name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm" # cache is fine; it doesn't install pnpm

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version
          which pnpm

      - name: Install deps (frontend)
        run: pnpm install || echo "no package.json yet"

      - name: Lint
        run: pnpm run lint || echo "no lint yet"

      - name: Typecheck
        run: pnpm run typecheck || echo "no typecheck yet"

      - name: Test
        run: pnpm test -- --coverage || echo "no tests yet"
